### ISSUE TITLE
iPad iOS > 12 detected as MacOS

### ISSUE THREAD

**Issue by smatoox** [matomo-org/device-detector#6398]
Hi,

I notice iPad iOS > 12 are detected like desktop Mac.

_All test done with Browserstack_

### iPad Pro 12.9 2018 - iOS 12
UA: `Mozilla/5.0 (iPad; CPU OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1`
Detector JS is OK: Mobile Safari, iOS

### iPad Pro 12.9 2020 - iOS 13
UA: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15`

### iPad Pro 12.9 2020 - iOS 14
UA: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15`

Test are the same with iPad "classic" if iOS > 12 ipad are desktop.

iPhone 11 iOS 14 keep his user agent with iphone device (`Mozilla/5.0 (iPhone; CPU iPhone OS 14_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1`)

It will be difficult to detect the hardware now.
Hope people have ideas for testing.

**Comment by Findus23** [comment]
Hi,

This is intended by Apple. If you look at the user agent since iOS 12, then you see that they are detected as desktop Mac as they are the user agents of a desktop mac.

Apple didn't like that too many websites were serving mobile pages to iPads, so they changed the user agent to look like the one of Safari on macOS. If you select "request mobile page" on one website, iOS safari will send a iOS/iPad user agent to this website. If one dislikes this change, on can revert this change in the Safari settings.

see also https://github.com/matomo-org/device-detector/issues/6313

**Comment by smatoox** [comment]
Thanks for the clarification.
Apple...
Maybe we can update detection with touch event + screen width/height

**Comment by sanchezzzhak** [comment]
> Thanks for the clarification.
> Apple...
> Maybe we can update detection with touch event + screen width/height

this is not possible, we use the device definition on the server by the useragent string
client properties from JS are not available for the web server

**Comment by Tammychmarney** [comment]
Device
Intel Mac OS X 10_15_6

**Comment by Tammychmarney** [comment]
GitHub Canada as Tammychmarney
