### ISSUE TITLE
Parsing mismatches between versions

### ISSUE THREAD

**Issue by webmake** [matomo-org/device-detector#6418]
Hello,
Now I am checking 4version how it changed since 3.11.8, and have to say it is going better and better, but now I am getting some weird transformations
```
"Mozilla/5.0 (Linux; diordnA 9) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/8.0.9 Chrome/85.0.4183.127 eliboM Safari/537.36"
	desktop ->  ""
"Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/537.36 (KHTML, like Gecko) Safari/537.36 VivoBrowser/6.8.0.1 Chrome/62.0.3202.84"
	smartphone ->  ""
"Mozilla/5.0 (Windows; U; Windows NT 5.2;. en-US) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.108 Safari/537.36 UCTurbo/1.9.8.900"
	desktop ->  ""
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/61.0.3163.128 Safari/534.24 XiaoMi/Mint Browser/3.6.0"
	smartphone ->  "desktop"
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Safari/537.36 mCent/0.13.1214"
	desktop ->  ""
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Safari/537.36 Edg/77.07.4.5059"
	desktop ->  "smartphone"
```

Could you confirm is it okay?
Wasn't solved reverse (android->diordnA) user agent that we was discussing on https://github.com/matomo-org/device-detector/issues/6152 ?

**Comment by sgiehl** [comment]
> "Mozilla/5.0 (Linux; diordnA 9) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/8.0.9 Chrome/85.0.4183.127 eliboM Safari/537.36"
>	desktop ->  ""

sounds imho legit, but it's not detected as an Android device. Maybe we could add a reverse detection for that

> "Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/537.36 (KHTML, like Gecko) Safari/537.36 VivoBrowser/6.8.0.1 Chrome/62.0.3202.84"
> 	smartphone ->  ""

That's correct. Seems it was detected as a Vivo smartphone before.

> "Mozilla/5.0 (Windows; U; Windows NT 5.2;. en-US) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.108 Safari/537.36 UCTurbo/1.9.8.900"
> 	desktop ->  ""

That's because the UCTurbo browser is now detected. But the results seem to be a bit weird. A Windows 2003 running a UC Browser Turbo, which is marked as a mobile only browser 🤔 

> "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/61.0.3163.128 Safari/534.24 XiaoMi/Mint Browser/3.6.0"
> 	smartphone ->  "desktop"

That's correct. Before it was detected as a Xiaomi device, which was incorrect. Nevertheless I've just seen the OS of this useragent is detected as `Mint`, which seems incorrect. Should be simply Linux, as the Mint is a browser identifier in this case.

> "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Safari/537.36 mCent/0.13.1214"
> 	desktop ->  ""

Seems legit. Detection for mCent browser was added, which is currently a android only browser

> "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Safari/537.36 Edg/77.07.4.5059"
> desktop ->  "smartphone"

that one is an incorrect change. Guess we need to harden the check for Advan devices here, as it's detected as Advan 5059


@sanchezzzhak do you have some time to provide some fixes for the invalid changes?

**Comment by sanchezzzhak** [comment]
I think so.

**Comment by sgiehl** [comment]
@sanchezzzhak thanks for the fixes.
@webmake the remaining changes seem legit. Will release a new version in the next couple of hours
