### ISSUE TITLE
Bug on Mobile?

### ISSUE THREAD

**Issue by alexolliveira** [matomo-org/device-detector#7531]
Some features doesn't work on Chrome 120 on Android(10): getModel() and getBrandName() are showing **string(0) ""**

**Comment by liviuconcioiu** [comment]
There's no bug. You can't get the Brand and Model because of reduced user agent. See https://developers.google.com/privacy-sandbox/protections/user-agent.

`Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36`

You need to pass client hints, like here https://github.com/matomo-org/device-detector#usage.
