### ISSUE TITLE
Amazon Fire TV Detection by Build Models

### ISSUE THREAD

**Issue by EfekanPekel** [matomo-org/device-detector#7539]
https://developer.amazon.com/docs/fire-tv/identify-amazon-fire-tv-devices.html

Amazon gives the device details by build model. However, some build models refer to multiple devices.

Mozilla/5.0 (Linux; Android 9; AFTKAUK002) AppleWebKit/537.36 (KHTML, like Gecko) Silk/118.3.1 like Chrome/118.0.5993.155 Safari/537.36
Model: Fire TV 2-Series (2023)  (Search AFTKAUK002 on the link.)

Mozilla/5.0 (Linux; Android 9; AFTANNA0 Build/PS7664.3772N; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36
Device: tv, Brand: Xiaomi F2 4K - Fire TV (2022) or ok 4K - Fire TV (2021) (Search AFTANNA0 on the given link)

Does this make sense for detection?

**Comment by sanchezzzhak** [comment]
make sense.  I think it's worth considering "AFTANNA0" as brand: `Ok` model: `UHD Smart Fire TV (2021)`

**Comment by liviuconcioiu** [comment]
`AFTANNA0` was already being detected, but under different regexes. I've added a general regex (`Fire TV (2021-2022)`) since there might be more brands using it. So far there are three.

https://github.com/matomo-org/device-detector/blob/30463d57dd2afe06a9ca61ddde2c37bdb85412d9/Tests/fixtures/tv-2.yml#L6188-L6205
https://github.com/matomo-org/device-detector/blob/30463d57dd2afe06a9ca61ddde2c37bdb85412d9/Tests/fixtures/tv-2.yml#L6242-L6259

**Comment by EfekanPekel** [comment]
Please check the rest of the document. There are a lot more devices, especially not Amazon production devices like TCL, Grundig and etc.

https://developer.amazon.com/docs/fire-tv/identify-amazon-fire-tv-devices.html

**Comment by liviuconcioiu** [comment]
> Please check the rest of the document. There are a lot more devices, especially not Amazon production devices like TCL, Grundig and etc.

I agree that some devices aren't detected (I'll handle the missing ones in another PR), but for some is impossible to specify an exact brand/model. The best way to detect them is:

```
brand: Amazon
model: Fire TV (year)
```
